arch: checks for the exist of codesinger when buildtime.
In Boards such as ARTIK053s or ARTIK055s, in order to create the correct
image must have to the codesigner tool. But Currently, TizenRT doesn't
check exist of codesinger when buildtime. This patch add config for path
of codesigner in Kconfig and check for exist of codesigner at build time.

Change-Id: I4805c8026740eaf12f1c1e778d70518f540e84ba
Signed-off-by: Jihun Ahn <jhun.ahn@samsung.com>
Signed-off-by: Junhwan Park <junhwan.park@samsung.com>

diff --git a/os/arch/arm/src/artik05x/src/Makefile b/os/arch/arm/src/artik05x/src/Makefile
--- a/os/arch/arm/src/artik05x/src/Makefile
+++ b/os/arch/arm/src/artik05x/src/Makefile
@@ -100,7 +100,28 @@ else
   CFLAGS += -I$(ARCH_SRCDIR)/armv7-r
 endif
 
+ifeq ($(CONFIG_ARTIK05X_SECURE),y)
+CODESIGNEREXE := $(TOPDIR)/$(CONFIG_ARTIK05X_CODESIGNER_PATH)
+else
+CODESIGNEREXE :=
+endif
+
 all: libboard$(LIBEXT)
+
+context:
+ifeq ($(CONFIG_ARTIK05X_SECURE),y)
+	$(Q) if [ ! -x $(CODESIGNEREXE) ]; then \
+		echo ""; \
+		echo "ERROR: cannot find codesigner ${CONFIG_ARTIK05X_CODESIGNER_PATH}"; \
+		echo "Build process has been terminated since the mandatory security binaries do not exist in your source code."; \
+		echo "Please download those files from artik.io with SLA agreement to continue to build."; \
+		echo "Once you download those files, please locate them to the following path."; \
+		echo ""; \
+		echo "copy to ${CODESIGNEREXE}"; \
+		echo ""; \
+		exit 1; \
+	fi
+endif
 
 $(AOBJS): %$(OBJEXT): %.S
 	$(call ASSEMBLE, $<, $@)
